//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backToSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Attendance_Detail
    {
        public string Student_Id { get; set; }
        public int Attendance_Id { get; set; }
        public bool Attend { get; set; }
        public string Notes { get; set; }
        public bool Status { get; set; }
    
        public virtual Class_Attendance Class_Attendance { get; set; }
        public virtual Student Student { get; set; }
    }
}
