//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backToSchool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBschool : DbContext
    {
        public DBschool()
            : base("name=DBschool")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announce> Announces { get; set; }
        public virtual DbSet<Class_Attendance> Class_Attendance { get; set; }
        public virtual DbSet<Class_Attendance_Detail> Class_Attendance_Detail { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Group_Attendance> Group_Attendance { get; set; }
        public virtual DbSet<Index> Indices { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Relative> Relatives { get; set; }
        public virtual DbSet<Responsible_Letter> Responsible_Letter { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<School_Setup> School_Setup { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Relative> Student_Relative { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
