//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backToSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsible_Letter
    {
        public string Student_Id { get; set; }
        public System.DateTime Letter_Date { get; set; }
        public bool COVID_19 { get; set; }
        public bool COVID_19_Relatives { get; set; }
        public bool Cough { get; set; }
        public bool Fever { get; set; }
        public bool Fatigue { get; set; }
        public bool Throat_Pain { get; set; }
        public bool Nasal_Congestion { get; set; }
        public bool Respiratory_Difficulty { get; set; }
        public bool Diarrhea { get; set; }
        public bool Cold_Symptoms { get; set; }
        public bool Is_Signed { get; set; }
        public Nullable<System.DateTime> Signed_Time { get; set; }
        public bool Global_Attendance { get; set; }
        public string Relative_Id { get; set; }
    
        public virtual Relative Relative { get; set; }
        public virtual Student Student { get; set; }
    }
}
