//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backToSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Setup
    {
        public string School_Id { get; set; }
        public int Max_Capacity { get; set; }
        public int Last_Max_Capacity { get; set; }
        public int School_Miss_Penalization { get; set; }
    
        public virtual School School { get; set; }
    }
}
