//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backToSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Class_Attendance_Detail = new HashSet<Class_Attendance_Detail>();
            this.Responsible_Letter = new HashSet<Responsible_Letter>();
            this.Student_Relative = new HashSet<Student_Relative>();
            this.Groups = new HashSet<Group>();
        }
    
        public string Student_Id { get; set; }
        public string Student_Name { get; set; }
        public string Student_Last_Name { get; set; }
        public bool Student_Available { get; set; }
        public bool Student_Status { get; set; }
        public string Student_Sex { get; set; }
        public string Student_Photo { get; set; }
        public string School_Id { get; set; }
        public int Shift_Id { get; set; }
        public int Grade_Id { get; set; }
        public int Index_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Attendance_Detail> Class_Attendance_Detail { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Index Index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responsible_Letter> Responsible_Letter { get; set; }
        public virtual School School { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Relative> Student_Relative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
    }
}
