//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backToSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string User_Id { get; set; }
        public string User_Password { get; set; }
        public System.DateTime User_Last_Login { get; set; }
        public System.DateTime User_Created { get; set; }
        public int Role_Id { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
